# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/data/UnrealEngine5.5.4

TARGETS = \
	TPSCoreMechanics-Android-DebugGame  \
	TPSCoreMechanics-Android-Development  \
	TPSCoreMechanics-Android-Shipping  \
	TPSCoreMechanics-Linux-DebugGame  \
	TPSCoreMechanics-Linux-Development  \
	TPSCoreMechanics-Linux-Shipping  \
	TPSCoreMechanics-LinuxArm64-DebugGame  \
	TPSCoreMechanics-LinuxArm64-Development  \
	TPSCoreMechanics-LinuxArm64-Shipping  \
	TPSCoreMechanics \
	TPSCoreMechanicsEditor-Linux-DebugGame  \
	TPSCoreMechanicsEditor-Linux-Development  \
	TPSCoreMechanicsEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TPSCoreMechanicsEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TPSCoreMechanicsEditor-Linux-Debug


TPSCoreMechanics-Android-DebugGame:
	 $(BUILD) TPSCoreMechanics Android DebugGame  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-Android-Development:
	 $(BUILD) TPSCoreMechanics Android Development  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-Android-Shipping:
	 $(BUILD) TPSCoreMechanics Android Shipping  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-Linux-DebugGame:
	 $(BUILD) TPSCoreMechanics Linux DebugGame  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-Linux-Development:
	 $(BUILD) TPSCoreMechanics Linux Development  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-Linux-Shipping:
	 $(BUILD) TPSCoreMechanics Linux Shipping  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-LinuxArm64-DebugGame:
	 $(BUILD) TPSCoreMechanics LinuxArm64 DebugGame  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-LinuxArm64-Development:
	 $(BUILD) TPSCoreMechanics LinuxArm64 Development  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics-LinuxArm64-Shipping:
	 $(BUILD) TPSCoreMechanics LinuxArm64 Shipping  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanics: TPSCoreMechanics-Linux-Development

TPSCoreMechanicsEditor-Linux-DebugGame:
	 $(BUILD) TPSCoreMechanicsEditor Linux DebugGame  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanicsEditor-Linux-Development:
	 $(BUILD) TPSCoreMechanicsEditor Linux Development  -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" $(ARGS)

TPSCoreMechanicsEditor: TPSCoreMechanicsEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/media/skyne/Data/Projects/idklol-client/TPSCoreMechanics.uproject" -Game 

.PHONY: $(TARGETS)
