//Generated by TurboLink CodeGenerator, do not edit!
#include "ChatService_Private.h"

void UChatServiceMessageLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnMessageResponse.RemoveDynamic(this, &UChatServiceMessageLambdaWrapper::OnResponse);
}

void UChatServiceStreamLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcChatChatMessage& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
}

void UChatServiceStreamLambdaWrapper::OnContextStateChanged(FGrpcContextHandle _Handle, EGrpcContextState NewState)
{
	if (_Handle != this->Handle) return;
	if (NewState == EGrpcContextState::Done)
	{
		FinishLambda();

		InnerClient->OnStreamResponse.RemoveDynamic(this, &UChatServiceStreamLambdaWrapper::OnResponse);
		InnerClient->OnContextStateChange.RemoveDynamic(this, &UChatServiceStreamLambdaWrapper::OnContextStateChanged);
	}
}

