//Generated by TurboLink CodeGenerator, do not edit!
#include "ChatContext.h"
#include "SChat/ChatClient.h"
#include "ChatService_Private.h"
#include "ChatMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "TurboLinkGrpcManager.h"

GrpcContext_ChatService_Message::GrpcContext_ChatService_Message(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ChatService_Message::Call(const FGrpcChatChatMessage& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::chat::ChatMessage rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UChatService* service = (UChatService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncMessage(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_ChatService_Message::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::google::protobuf::Empty* _RpcResponse) 
		{
			UChatServiceClient* client = (UChatServiceClient*)(this->Client);
			if (!(client->OnMessageResponse.IsBound())) return;

			FGrpcGoogleProtobufEmpty response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnMessageResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_ChatService_Stream::GrpcContext_ChatService_Stream(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_ChatService_Stream::Call(const FGrpcGoogleProtobufEmpty& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::google::protobuf::Empty rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UChatService* service = (UChatService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncStream(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get(), InitialTag);
}

void GrpcContext_ChatService_Stream::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::chat::ChatMessage* _RpcResponse) 
		{
			UChatServiceClient* client = (UChatServiceClient*)(this->Client);
			if (!(client->OnStreamResponse.IsBound())) return;

			FGrpcChatChatMessage response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnStreamResponse.Broadcast(Handle, _Result, response);
		}
	);
}
