//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SChat/ChatMessage.h"
#include "TurboLinkGrpcContext.h"
#include "chat.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::chat::ChatMessage* in, FGrpcChatChatMessage* out);
void TURBOLINK_TO_GRPC(const FGrpcChatChatMessage* in, ::chat::ChatMessage* out);

typedef grpc::ClientAsyncResponseReader<::google::protobuf::Empty> ChatService_Message_ReaderWriter;
typedef grpc::ClientAsyncReader<::chat::ChatMessage> ChatService_Stream_ReaderWriter;
