//Generated by TurboLink CodeGenerator, do not edit!
#include "SChat/ChatService.h"
#include "SChat/ChatClient.h"
#include "ChatService_Private.h"
#include "ChatMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UChatService::UChatService()
	: d(new UChatService::Private())
{
}

UChatService::~UChatService()
{
	delete d;
}

void UChatService::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("ChatService"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to ChatService: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel((const char*)StringCast<UTF8CHAR>(*serviceEndPoint).Get(), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = chat::ChatService::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UChatService::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UChatServiceClient* UChatService::MakeClient()
{
	auto client = UGrpcService::MakeClient<UChatServiceClient>();
	return client;
}

void UChatService::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UChatService::CallMessage(const FGrpcChatChatMessage& Request, FMessageResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceMessageLambdaWrapper* lambdaWrapper = NewObject<UChatServiceMessageLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitMessage();
	InnerClient->OnMessageResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceMessageLambdaWrapper::OnResponse);
	InnerClient->Message(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}

void UChatService::CallStream(const FGrpcGoogleProtobufEmpty& Request, FStreamResponseLambda ResponseLambda, FStreamFinishLambda FinishLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UChatServiceStreamLambdaWrapper* lambdaWrapper = NewObject<UChatServiceStreamLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->FinishLambda = FinishLambda;
	lambdaWrapper->Handle = InnerClient->InitStream();
	InnerClient->OnStreamResponse.AddUniqueDynamic(lambdaWrapper, &UChatServiceStreamLambdaWrapper::OnResponse);
	InnerClient->OnContextStateChange.AddUniqueDynamic(lambdaWrapper, &UChatServiceStreamLambdaWrapper::OnContextStateChanged);
	InnerClient->Stream(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}
