//Generated by TurboLink CodeGenerator, do not edit!
#include "SChat/ChatMessage.h"
#include "SChat/ChatMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcChatChatMessage, ::chat::ChatMessage)

