//Generated by TurboLink CodeGenerator, do not edit!
#include "ChatMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"

void GRPC_TO_TURBOLINK(const ::chat::ChatMessage* in, FGrpcChatChatMessage* out)
{
    out->Timestamp=StringCast<TCHAR>((const UTF8CHAR*)(in->timestamp().c_str())).Get();
    out->Sender=StringCast<TCHAR>((const UTF8CHAR*)(in->sender().c_str())).Get();
    out->Message=StringCast<TCHAR>((const UTF8CHAR*)(in->message().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcChatChatMessage* in, ::chat::ChatMessage* out)
{
    out->set_timestamp((const char*)StringCast<UTF8CHAR>(*(in->Timestamp)).Get());
    out->set_sender((const char*)StringCast<UTF8CHAR>(*(in->Sender)).Get());
    out->set_message((const char*)StringCast<UTF8CHAR>(*(in->Message)).Get());
}

