//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SChat/ChatMessage.h"
#include "SChat/ChatMarshaling.h"
class GrpcContext_ChatService_Message : public GrpcContext_Ping_Pong<ChatService_Message_ReaderWriter, ::google::protobuf::Empty>
{
	friend class UChatServiceClient;
	typedef GrpcContext_Ping_Pong<ChatService_Message_ReaderWriter, ::google::protobuf::Empty> Super;

private:
	void Call(const FGrpcChatChatMessage& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_ChatService_Message(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_ChatService_Stream : public GrpcContext_Ping_Stream<ChatService_Stream_ReaderWriter, ::chat::ChatMessage>
{
	friend class UChatServiceClient;
	typedef GrpcContext_Ping_Stream<ChatService_Stream_ReaderWriter, ::chat::ChatMessage> Super;

private:
	void Call(const FGrpcGoogleProtobufEmpty& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_ChatService_Stream(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

