//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SChat/ChatService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "chat.grpc.pb.h"
#include "ChatService_Private.generated.h"

class UChatService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::chat::ChatService::Stub> Stub;
};


UCLASS()
class UChatServiceMessageLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UChatServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);
public:
	FGrpcContextHandle Handle;
	UChatService::FMessageResponseLambda ResponseLambda;
};

UCLASS()
class UChatServiceStreamLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UChatServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcChatChatMessage& Response);
	UFUNCTION()
	void OnContextStateChanged(FGrpcContextHandle Handle, EGrpcContextState NewState);
public:
	FGrpcContextHandle Handle;
	UChatService::FStreamResponseLambda ResponseLambda;
	UChatService::FStreamFinishLambda FinishLambda;
};

