//Generated by TurboLink CodeGenerator, do not edit!
#include "SChat/ChatNode.h"
#include "SChat/ChatService.h"
#include "TurboLinkGrpcManager.h"
#include "TurboLinkGrpcUtilities.h"
#include "Engine/World.h"
#include "TimerManager.h"
#include "Runtime/Launch/Resources/Version.h"

UCallChatServiceMessage* UCallChatServiceMessage::Message(UObject* WorldContextObject, const FGrpcChatChatMessage& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallChatServiceMessage* node = NewObject<UCallChatServiceMessage>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->ChatService = Cast<UChatService>(turboLinkManager->MakeService("ChatService"));
	if (node->ChatService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->ChatService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallChatServiceMessage::OnServiceStateChanged);
	return node;
}

void UCallChatServiceMessage::Activate()
{
	ChatService->Connect();
}

void UCallChatServiceMessage::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcGoogleProtobufEmpty response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		ChatServiceClient = ChatService->MakeClient();
		ChatServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallChatServiceMessage::OnContextStateChange);
		ChatServiceClient->OnMessageResponse.AddUniqueDynamic(this, &UCallChatServiceMessage::OnResponse);

		Context = ChatServiceClient->InitMessage();
		ChatServiceClient->Message(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallChatServiceMessage::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallChatServiceMessage::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnMessageResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallChatServiceMessage::Shutdown()
{
	ChatService->OnServiceStateChanged.RemoveDynamic(this, &UCallChatServiceMessage::OnServiceStateChanged);
	if (ChatServiceClient != nullptr)
	{
		ChatService->RemoveClient(ChatServiceClient);
		ChatServiceClient->Shutdown();
		ChatServiceClient = nullptr;
	}

	if (ChatService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(ChatService);
		ChatService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}

UCallChatServiceStream* UCallChatServiceStream::Stream(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallChatServiceStream* node = NewObject<UCallChatServiceStream>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->ChatService = Cast<UChatService>(turboLinkManager->MakeService("ChatService"));
	if (node->ChatService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->ChatService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallChatServiceStream::OnServiceStateChanged);
	return node;
}

void UCallChatServiceStream::Activate()
{
	ChatService->Connect();
}

void UCallChatServiceStream::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcChatChatMessage response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		ChatServiceClient = ChatService->MakeClient();
		ChatServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallChatServiceStream::OnContextStateChange);
		ChatServiceClient->OnStreamResponse.AddUniqueDynamic(this, &UCallChatServiceStream::OnResponse);

		Context = ChatServiceClient->InitStream();
		ChatServiceClient->Stream(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallChatServiceStream::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		OnFinished.Broadcast(FGrpcResult{}, FGrpcChatChatMessage{});
		Shutdown();
	}
}

void UCallChatServiceStream::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcChatChatMessage& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnStreamResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallChatServiceStream::Shutdown()
{
	ChatService->OnServiceStateChanged.RemoveDynamic(this, &UCallChatServiceStream::OnServiceStateChanged);
	if (ChatServiceClient != nullptr)
	{
		ChatService->RemoveClient(ChatServiceClient);
		ChatServiceClient->Shutdown();
		ChatServiceClient = nullptr;
	}

	if (ChatService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(ChatService);
		ChatService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}
