//Generated by TurboLink CodeGenerator, do not edit!
#include "SChat/ChatClient.h"
#include "SChat/ChatService.h"
#include "ChatContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UChatServiceClient::InitMessage()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_ChatService_Message>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UChatServiceClient::Message(FGrpcContextHandle Handle, const FGrpcChatChatMessage& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextMessage = StaticCastSharedPtr<GrpcContext_ChatService_Message>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextMessage->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextMessage->RpcContext->set_deadline(deadLine);
		}
		contextMessage->Call(Request);
	}
}

FGrpcContextHandle UChatServiceClient::InitStream()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_ChatService_Stream>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UChatServiceClient::Stream(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextStream = StaticCastSharedPtr<GrpcContext_ChatService_Stream>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextStream->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextStream->RpcContext->set_deadline(deadLine);
		}
		contextStream->Call(Request);
	}
}

void UChatServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UChatServiceClient::Shutdown()
{
	OnMessageResponse.Clear();
	OnStreamResponse.Clear();
	Super::Shutdown();
}

