//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SChat/ChatClient.h"
#include "ChatService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UChatService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UChatServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UChatServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)> FMessageResponseLambda;
	void CallMessage(const FGrpcChatChatMessage& Request, FMessageResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcChatChatMessage& Response)> FStreamResponseLambda;
	typedef TFunction<void()> FStreamFinishLambda;
	void CallStream(const FGrpcGoogleProtobufEmpty& Request, FStreamResponseLambda ResponseLambda, FStreamFinishLambda FinishLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	class Private;
	Private* const d = nullptr;

public:
	UChatService();
	virtual ~UChatService();
};

