//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SChat/ChatMessage.h"
#include "ChatClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceMessageResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceStreamResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcChatChatMessage&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UChatServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnChatServiceMessageResponse OnMessageResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceStreamResponse OnStreamResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitMessage();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void Message(FGrpcContextHandle Handle, const FGrpcChatChatMessage& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitStream();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void Stream(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

