//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "ChatMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Chat.ChatMessage"))
struct FGrpcChatChatMessage : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Timestamp = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Sender = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";
};
