//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "ChatMessage.h"
#include "ChatNode.generated.h"

class UChatService;
class UChatServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceMessage : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceMessageDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|ChatService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call ChatService Message",
		AdvancedDisplay = 2))
	static UCallChatServiceMessage* Message(UObject* WorldContextObject, const FGrpcChatChatMessage& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FChatServiceMessageDelegate OnMessageResponse;

	UPROPERTY(BlueprintAssignable)
	FChatServiceMessageDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcChatChatMessage Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceStream : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceStreamDelegate, const FGrpcResult&, GrpcResult, const FGrpcChatChatMessage&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|ChatService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call ChatService Stream",
		AdvancedDisplay = 2))
	static UCallChatServiceStream* Stream(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FChatServiceStreamDelegate OnStreamResponse;

	UPROPERTY(BlueprintAssignable)
	FChatServiceStreamDelegate OnFinished;

	UPROPERTY(BlueprintAssignable)
	FChatServiceStreamDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGoogleProtobufEmpty Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcChatChatMessage& Response);

	void Shutdown();
};
