//Generated by TurboLink CodeGenerator, do not edit!
#include "SGoogleProtobuf/EmptyMessage.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcGoogleProtobufEmpty, ::google::protobuf::Empty)

