//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "CharactersMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Characters.Race", ScriptName="EGrpcCharactersRace"))
enum class EGrpcCharactersRace : uint8
{
    RACE_UNSPECIFIED=0,
    HUMAN=1,
    ELF=2,
    DWARF=3,
    ORC=4,
};

UENUM(BlueprintType, meta = (DisplayName="Characters.Gender", ScriptName="EGrpcCharactersGender"))
enum class EGrpcCharactersGender : uint8
{
    GENDER_UNSPECIFIED=0,
    MALE=1,
    FEMALE=2,
};

UENUM(BlueprintType, meta = (DisplayName="Characters.SkinColor", ScriptName="EGrpcCharactersSkinColor"))
enum class EGrpcCharactersSkinColor : uint8
{
    SKIN_COLOR_UNSPECIFIED=0,
    PALE=1,
    FAIR=2,
    TAN=3,
    BROWN=4,
    DARK=5,
    GREEN=6,
    GRAY=7,
};

UENUM(BlueprintType, meta = (DisplayName="Characters.CharacterClass", ScriptName="EGrpcCharactersCharacterClass"))
enum class EGrpcCharactersCharacterClass : uint8
{
    CLASS_UNSPECIFIED=0,
    WARRIOR=1,
    MAGE=2,
    ROGUE=3,
    CLERIC=4,
    RANGER=5,
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.CheckCharacterCreationCatalogVersionRequest"))
struct FGrpcCharactersCheckCharacterCreationCatalogVersionRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CachedVersion = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.CheckCharacterCreationCatalogVersionResponse"))
struct FGrpcCharactersCheckCharacterCreationCatalogVersionResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool IsCurrent = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString LatestVersion = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.RaceOption"))
struct FGrpcCharactersRaceOption : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.GenderOption"))
struct FGrpcCharactersGenderOption : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.SkinColorOption"))
struct FGrpcCharactersSkinColorOption : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersSkinColor SkinColor = static_cast<EGrpcCharactersSkinColor>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.ClassOption"))
struct FGrpcCharactersClassOption : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersCharacterClass CharacterClass = static_cast<EGrpcCharactersCharacterClass>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.RaceGenderCombination"))
struct FGrpcCharactersRaceGenderCombination : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.RaceGenderSkinColorCombination"))
struct FGrpcCharactersRaceGenderSkinColorCombination : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersSkinColor SkinColor = static_cast<EGrpcCharactersSkinColor>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.RaceGenderClassCombination"))
struct FGrpcCharactersRaceGenderClassCombination : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersCharacterClass CharacterClass = static_cast<EGrpcCharactersCharacterClass>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.CharacterCreationCatalog"))
struct FGrpcCharactersCharacterCreationCatalog : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Version = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersRaceOption> Races;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersGenderOption> Genders;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersSkinColorOption> SkinColors;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersClassOption> Classes;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersRaceGenderCombination> AllowedRaceGender;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersRaceGenderSkinColorCombination> AllowedRaceGenderSkinColor;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersRaceGenderClassCombination> AllowedRaceGenderClass;
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.CreateCharacterRequest"))
struct FGrpcCharactersCreateCharacterRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersSkinColor SkinColor = static_cast<EGrpcCharactersSkinColor>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersCharacterClass CharacterClass = static_cast<EGrpcCharactersCharacterClass>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.CreateCharacterResponse"))
struct FGrpcCharactersCreateCharacterResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CharacterId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersSkinColor SkinColor = static_cast<EGrpcCharactersSkinColor>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersCharacterClass CharacterClass = static_cast<EGrpcCharactersCharacterClass>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CreatedAt = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.ListCreatedCharactersRequest"))
struct FGrpcCharactersListCreatedCharactersRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.Character"))
struct FGrpcCharactersCharacter : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CharacterId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Name = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersRace Race = static_cast<EGrpcCharactersRace>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersGender Gender = static_cast<EGrpcCharactersGender>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersSkinColor SkinColor = static_cast<EGrpcCharactersSkinColor>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcCharactersCharacterClass CharacterClass = static_cast<EGrpcCharactersCharacterClass>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString CreatedAt = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Characters.ListCreatedCharactersResponse"))
struct FGrpcCharactersListCreatedCharactersResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcCharactersCharacter> Characters;
};
