//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SCharacters/CharactersMessage.h"
#include "CharactersClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceCheckCharacterCreationCatalogVersionResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceGetCharacterCreationCatalogResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcCharactersCharacterCreationCatalog&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceCreateCharacterResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcCharactersCreateCharacterResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnCharacterServiceListCreatedCharactersResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcCharactersListCreatedCharactersResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UCharacterServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceCheckCharacterCreationCatalogVersionResponse OnCheckCharacterCreationCatalogVersionResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceGetCharacterCreationCatalogResponse OnGetCharacterCreationCatalogResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceCreateCharacterResponse OnCreateCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FOnCharacterServiceListCreatedCharactersResponse OnListCreatedCharactersResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCheckCharacterCreationCatalogVersion();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CheckCharacterCreationCatalogVersion(FGrpcContextHandle Handle, const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetCharacterCreationCatalog();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetCharacterCreationCatalog(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateCharacter();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CreateCharacter(FGrpcContextHandle Handle, const FGrpcCharactersCreateCharacterRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitListCreatedCharacters();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void ListCreatedCharacters(FGrpcContextHandle Handle, const FGrpcCharactersListCreatedCharactersRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

