//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SCharacters/CharactersClient.h"
#include "CharactersService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UCharacterService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UCharacterServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UCharacterServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse& Response)> FCheckCharacterCreationCatalogVersionResponseLambda;
	void CallCheckCharacterCreationCatalogVersion(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request, FCheckCharacterCreationCatalogVersionResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcCharactersCharacterCreationCatalog& Response)> FGetCharacterCreationCatalogResponseLambda;
	void CallGetCharacterCreationCatalog(const FGrpcGoogleProtobufEmpty& Request, FGetCharacterCreationCatalogResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcCharactersCreateCharacterResponse& Response)> FCreateCharacterResponseLambda;
	void CallCreateCharacter(const FGrpcCharactersCreateCharacterRequest& Request, FCreateCharacterResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcCharactersListCreatedCharactersResponse& Response)> FListCreatedCharactersResponseLambda;
	void CallListCreatedCharacters(const FGrpcCharactersListCreatedCharactersRequest& Request, FListCreatedCharactersResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	class Private;
	Private* const d = nullptr;

public:
	UCharacterService();
	virtual ~UCharacterService();
};

