//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "CharactersMessage.h"
#include "CharactersNode.generated.h"

class UCharacterService;
class UCharacterServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallCharacterServiceCheckCharacterCreationCatalogVersion : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FCharacterServiceCheckCharacterCreationCatalogVersionDelegate, const FGrpcResult&, GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|CharacterService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call CharacterService CheckCharacterCreationCatalogVersion",
		AdvancedDisplay = 2))
	static UCallCharacterServiceCheckCharacterCreationCatalogVersion* CheckCharacterCreationCatalogVersion(UObject* WorldContextObject, const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceCheckCharacterCreationCatalogVersionDelegate OnCheckCharacterCreationCatalogVersionResponse;

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceCheckCharacterCreationCatalogVersionDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UCharacterService* CharacterService;
	
	UPROPERTY()
	UCharacterServiceClient* CharacterServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcCharactersCheckCharacterCreationCatalogVersionRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallCharacterServiceGetCharacterCreationCatalog : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FCharacterServiceGetCharacterCreationCatalogDelegate, const FGrpcResult&, GrpcResult, const FGrpcCharactersCharacterCreationCatalog&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|CharacterService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call CharacterService GetCharacterCreationCatalog",
		AdvancedDisplay = 2))
	static UCallCharacterServiceGetCharacterCreationCatalog* GetCharacterCreationCatalog(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceGetCharacterCreationCatalogDelegate OnGetCharacterCreationCatalogResponse;

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceGetCharacterCreationCatalogDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UCharacterService* CharacterService;
	
	UPROPERTY()
	UCharacterServiceClient* CharacterServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGoogleProtobufEmpty Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCharacterCreationCatalog& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallCharacterServiceCreateCharacter : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FCharacterServiceCreateCharacterDelegate, const FGrpcResult&, GrpcResult, const FGrpcCharactersCreateCharacterResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|CharacterService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call CharacterService CreateCharacter",
		AdvancedDisplay = 2))
	static UCallCharacterServiceCreateCharacter* CreateCharacter(UObject* WorldContextObject, const FGrpcCharactersCreateCharacterRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceCreateCharacterDelegate OnCreateCharacterResponse;

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceCreateCharacterDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UCharacterService* CharacterService;
	
	UPROPERTY()
	UCharacterServiceClient* CharacterServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcCharactersCreateCharacterRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCreateCharacterResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallCharacterServiceListCreatedCharacters : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FCharacterServiceListCreatedCharactersDelegate, const FGrpcResult&, GrpcResult, const FGrpcCharactersListCreatedCharactersResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|CharacterService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call CharacterService ListCreatedCharacters",
		AdvancedDisplay = 2))
	static UCallCharacterServiceListCreatedCharacters* ListCreatedCharacters(UObject* WorldContextObject, const FGrpcCharactersListCreatedCharactersRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceListCreatedCharactersDelegate OnListCreatedCharactersResponse;

	UPROPERTY(BlueprintAssignable)
	FCharacterServiceListCreatedCharactersDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UCharacterService* CharacterService;
	
	UPROPERTY()
	UCharacterServiceClient* CharacterServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcCharactersListCreatedCharactersRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersListCreatedCharactersResponse& Response);

	void Shutdown();
};
