//Generated by TurboLink CodeGenerator, do not edit!
#include "AuthService_Private.h"

void UAuthServiceLoginLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcAuthLoginResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnLoginResponse.RemoveDynamic(this, &UAuthServiceLoginLambdaWrapper::OnResponse);
}

