//Generated by TurboLink CodeGenerator, do not edit!
#include "SAuth/AuthClient.h"
#include "SAuth/AuthService.h"
#include "AuthContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UAuthServiceClient::InitLogin()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_AuthService_Login>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UAuthServiceClient::Login(FGrpcContextHandle Handle, const FGrpcAuthLoginRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextLogin = StaticCastSharedPtr<GrpcContext_AuthService_Login>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextLogin->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextLogin->RpcContext->set_deadline(deadLine);
		}
		contextLogin->Call(Request);
	}
}

void UAuthServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UAuthServiceClient::Shutdown()
{
	OnLoginResponse.Clear();
	Super::Shutdown();
}

