//Generated by TurboLink CodeGenerator, do not edit!
#include "SCharacters/CharactersService.h"
#include "SCharacters/CharactersClient.h"
#include "CharactersService_Private.h"
#include "CharactersMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UCharacterService::UCharacterService()
	: d(new UCharacterService::Private())
{
}

UCharacterService::~UCharacterService()
{
	delete d;
}

void UCharacterService::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("CharacterService"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to CharacterService: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel((const char*)StringCast<UTF8CHAR>(*serviceEndPoint).Get(), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = characters::CharacterService::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UCharacterService::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UCharacterServiceClient* UCharacterService::MakeClient()
{
	auto client = UGrpcService::MakeClient<UCharacterServiceClient>();
	return client;
}

void UCharacterService::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UCharacterService::CallCheckCharacterCreationCatalogVersion(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request, FCheckCharacterCreationCatalogVersionResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper* lambdaWrapper = NewObject<UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitCheckCharacterCreationCatalogVersion();
	InnerClient->OnCheckCharacterCreationCatalogVersionResponse.AddUniqueDynamic(lambdaWrapper, &UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper::OnResponse);
	InnerClient->CheckCharacterCreationCatalogVersion(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}

void UCharacterService::CallGetCharacterCreationCatalog(const FGrpcGoogleProtobufEmpty& Request, FGetCharacterCreationCatalogResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UCharacterServiceGetCharacterCreationCatalogLambdaWrapper* lambdaWrapper = NewObject<UCharacterServiceGetCharacterCreationCatalogLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitGetCharacterCreationCatalog();
	InnerClient->OnGetCharacterCreationCatalogResponse.AddUniqueDynamic(lambdaWrapper, &UCharacterServiceGetCharacterCreationCatalogLambdaWrapper::OnResponse);
	InnerClient->GetCharacterCreationCatalog(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}

void UCharacterService::CallCreateCharacter(const FGrpcCharactersCreateCharacterRequest& Request, FCreateCharacterResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UCharacterServiceCreateCharacterLambdaWrapper* lambdaWrapper = NewObject<UCharacterServiceCreateCharacterLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitCreateCharacter();
	InnerClient->OnCreateCharacterResponse.AddUniqueDynamic(lambdaWrapper, &UCharacterServiceCreateCharacterLambdaWrapper::OnResponse);
	InnerClient->CreateCharacter(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}

void UCharacterService::CallListCreatedCharacters(const FGrpcCharactersListCreatedCharactersRequest& Request, FListCreatedCharactersResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UCharacterServiceListCreatedCharactersLambdaWrapper* lambdaWrapper = NewObject<UCharacterServiceListCreatedCharactersLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitListCreatedCharacters();
	InnerClient->OnListCreatedCharactersResponse.AddUniqueDynamic(lambdaWrapper, &UCharacterServiceListCreatedCharactersLambdaWrapper::OnResponse);
	InnerClient->ListCreatedCharacters(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}
