//Generated by TurboLink CodeGenerator, do not edit!
#include "SCharacters/CharactersNode.h"
#include "SCharacters/CharactersService.h"
#include "TurboLinkGrpcManager.h"
#include "TurboLinkGrpcUtilities.h"
#include "Engine/World.h"
#include "TimerManager.h"
#include "Runtime/Launch/Resources/Version.h"

UCallCharacterServiceCheckCharacterCreationCatalogVersion* UCallCharacterServiceCheckCharacterCreationCatalogVersion::CheckCharacterCreationCatalogVersion(UObject* WorldContextObject, const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallCharacterServiceCheckCharacterCreationCatalogVersion* node = NewObject<UCallCharacterServiceCheckCharacterCreationCatalogVersion>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->CharacterService = Cast<UCharacterService>(turboLinkManager->MakeService("CharacterService"));
	if (node->CharacterService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->CharacterService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnServiceStateChanged);
	return node;
}

void UCallCharacterServiceCheckCharacterCreationCatalogVersion::Activate()
{
	CharacterService->Connect();
}

void UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcCharactersCheckCharacterCreationCatalogVersionResponse response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		CharacterServiceClient = CharacterService->MakeClient();
		CharacterServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnContextStateChange);
		CharacterServiceClient->OnCheckCharacterCreationCatalogVersionResponse.AddUniqueDynamic(this, &UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnResponse);

		Context = CharacterServiceClient->InitCheckCharacterCreationCatalogVersion();
		CharacterServiceClient->CheckCharacterCreationCatalogVersion(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnCheckCharacterCreationCatalogVersionResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallCharacterServiceCheckCharacterCreationCatalogVersion::Shutdown()
{
	CharacterService->OnServiceStateChanged.RemoveDynamic(this, &UCallCharacterServiceCheckCharacterCreationCatalogVersion::OnServiceStateChanged);
	if (CharacterServiceClient != nullptr)
	{
		CharacterService->RemoveClient(CharacterServiceClient);
		CharacterServiceClient->Shutdown();
		CharacterServiceClient = nullptr;
	}

	if (CharacterService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(CharacterService);
		CharacterService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}

UCallCharacterServiceGetCharacterCreationCatalog* UCallCharacterServiceGetCharacterCreationCatalog::GetCharacterCreationCatalog(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallCharacterServiceGetCharacterCreationCatalog* node = NewObject<UCallCharacterServiceGetCharacterCreationCatalog>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->CharacterService = Cast<UCharacterService>(turboLinkManager->MakeService("CharacterService"));
	if (node->CharacterService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->CharacterService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallCharacterServiceGetCharacterCreationCatalog::OnServiceStateChanged);
	return node;
}

void UCallCharacterServiceGetCharacterCreationCatalog::Activate()
{
	CharacterService->Connect();
}

void UCallCharacterServiceGetCharacterCreationCatalog::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcCharactersCharacterCreationCatalog response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		CharacterServiceClient = CharacterService->MakeClient();
		CharacterServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallCharacterServiceGetCharacterCreationCatalog::OnContextStateChange);
		CharacterServiceClient->OnGetCharacterCreationCatalogResponse.AddUniqueDynamic(this, &UCallCharacterServiceGetCharacterCreationCatalog::OnResponse);

		Context = CharacterServiceClient->InitGetCharacterCreationCatalog();
		CharacterServiceClient->GetCharacterCreationCatalog(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallCharacterServiceGetCharacterCreationCatalog::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallCharacterServiceGetCharacterCreationCatalog::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCharacterCreationCatalog& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnGetCharacterCreationCatalogResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallCharacterServiceGetCharacterCreationCatalog::Shutdown()
{
	CharacterService->OnServiceStateChanged.RemoveDynamic(this, &UCallCharacterServiceGetCharacterCreationCatalog::OnServiceStateChanged);
	if (CharacterServiceClient != nullptr)
	{
		CharacterService->RemoveClient(CharacterServiceClient);
		CharacterServiceClient->Shutdown();
		CharacterServiceClient = nullptr;
	}

	if (CharacterService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(CharacterService);
		CharacterService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}

UCallCharacterServiceCreateCharacter* UCallCharacterServiceCreateCharacter::CreateCharacter(UObject* WorldContextObject, const FGrpcCharactersCreateCharacterRequest& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallCharacterServiceCreateCharacter* node = NewObject<UCallCharacterServiceCreateCharacter>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->CharacterService = Cast<UCharacterService>(turboLinkManager->MakeService("CharacterService"));
	if (node->CharacterService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->CharacterService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallCharacterServiceCreateCharacter::OnServiceStateChanged);
	return node;
}

void UCallCharacterServiceCreateCharacter::Activate()
{
	CharacterService->Connect();
}

void UCallCharacterServiceCreateCharacter::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcCharactersCreateCharacterResponse response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		CharacterServiceClient = CharacterService->MakeClient();
		CharacterServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallCharacterServiceCreateCharacter::OnContextStateChange);
		CharacterServiceClient->OnCreateCharacterResponse.AddUniqueDynamic(this, &UCallCharacterServiceCreateCharacter::OnResponse);

		Context = CharacterServiceClient->InitCreateCharacter();
		CharacterServiceClient->CreateCharacter(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallCharacterServiceCreateCharacter::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallCharacterServiceCreateCharacter::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCreateCharacterResponse& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnCreateCharacterResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallCharacterServiceCreateCharacter::Shutdown()
{
	CharacterService->OnServiceStateChanged.RemoveDynamic(this, &UCallCharacterServiceCreateCharacter::OnServiceStateChanged);
	if (CharacterServiceClient != nullptr)
	{
		CharacterService->RemoveClient(CharacterServiceClient);
		CharacterServiceClient->Shutdown();
		CharacterServiceClient = nullptr;
	}

	if (CharacterService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(CharacterService);
		CharacterService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}

UCallCharacterServiceListCreatedCharacters* UCallCharacterServiceListCreatedCharacters::ListCreatedCharacters(UObject* WorldContextObject, const FGrpcCharactersListCreatedCharactersRequest& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallCharacterServiceListCreatedCharacters* node = NewObject<UCallCharacterServiceListCreatedCharacters>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->CharacterService = Cast<UCharacterService>(turboLinkManager->MakeService("CharacterService"));
	if (node->CharacterService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->CharacterService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallCharacterServiceListCreatedCharacters::OnServiceStateChanged);
	return node;
}

void UCallCharacterServiceListCreatedCharacters::Activate()
{
	CharacterService->Connect();
}

void UCallCharacterServiceListCreatedCharacters::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcCharactersListCreatedCharactersResponse response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		CharacterServiceClient = CharacterService->MakeClient();
		CharacterServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallCharacterServiceListCreatedCharacters::OnContextStateChange);
		CharacterServiceClient->OnListCreatedCharactersResponse.AddUniqueDynamic(this, &UCallCharacterServiceListCreatedCharacters::OnResponse);

		Context = CharacterServiceClient->InitListCreatedCharacters();
		CharacterServiceClient->ListCreatedCharacters(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallCharacterServiceListCreatedCharacters::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallCharacterServiceListCreatedCharacters::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersListCreatedCharactersResponse& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnListCreatedCharactersResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallCharacterServiceListCreatedCharacters::Shutdown()
{
	CharacterService->OnServiceStateChanged.RemoveDynamic(this, &UCallCharacterServiceListCreatedCharacters::OnServiceStateChanged);
	if (CharacterServiceClient != nullptr)
	{
		CharacterService->RemoveClient(CharacterServiceClient);
		CharacterServiceClient->Shutdown();
		CharacterServiceClient = nullptr;
	}

	if (CharacterService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(CharacterService);
		CharacterService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}
