//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SCharacters/CharactersMessage.h"
#include "SCharacters/CharactersMarshaling.h"
class GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion : public GrpcContext_Ping_Pong<CharacterService_CheckCharacterCreationCatalogVersion_ReaderWriter, ::characters::CheckCharacterCreationCatalogVersionResponse>
{
	friend class UCharacterServiceClient;
	typedef GrpcContext_Ping_Pong<CharacterService_CheckCharacterCreationCatalogVersion_ReaderWriter, ::characters::CheckCharacterCreationCatalogVersionResponse> Super;

private:
	void Call(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_CharacterService_GetCharacterCreationCatalog : public GrpcContext_Ping_Pong<CharacterService_GetCharacterCreationCatalog_ReaderWriter, ::characters::CharacterCreationCatalog>
{
	friend class UCharacterServiceClient;
	typedef GrpcContext_Ping_Pong<CharacterService_GetCharacterCreationCatalog_ReaderWriter, ::characters::CharacterCreationCatalog> Super;

private:
	void Call(const FGrpcGoogleProtobufEmpty& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_CharacterService_GetCharacterCreationCatalog(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_CharacterService_CreateCharacter : public GrpcContext_Ping_Pong<CharacterService_CreateCharacter_ReaderWriter, ::characters::CreateCharacterResponse>
{
	friend class UCharacterServiceClient;
	typedef GrpcContext_Ping_Pong<CharacterService_CreateCharacter_ReaderWriter, ::characters::CreateCharacterResponse> Super;

private:
	void Call(const FGrpcCharactersCreateCharacterRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_CharacterService_CreateCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_CharacterService_ListCreatedCharacters : public GrpcContext_Ping_Pong<CharacterService_ListCreatedCharacters_ReaderWriter, ::characters::ListCreatedCharactersResponse>
{
	friend class UCharacterServiceClient;
	typedef GrpcContext_Ping_Pong<CharacterService_ListCreatedCharacters_ReaderWriter, ::characters::ListCreatedCharactersResponse> Super;

private:
	void Call(const FGrpcCharactersListCreatedCharactersRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_CharacterService_ListCreatedCharacters(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

