//Generated by TurboLink CodeGenerator, do not edit!
#include "SCharacters/CharactersClient.h"
#include "SCharacters/CharactersService.h"
#include "CharactersContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UCharacterServiceClient::InitCheckCharacterCreationCatalogVersion()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UCharacterServiceClient::CheckCharacterCreationCatalogVersion(FGrpcContextHandle Handle, const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextCheckCharacterCreationCatalogVersion = StaticCastSharedPtr<GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextCheckCharacterCreationCatalogVersion->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextCheckCharacterCreationCatalogVersion->RpcContext->set_deadline(deadLine);
		}
		contextCheckCharacterCreationCatalogVersion->Call(Request);
	}
}

FGrpcContextHandle UCharacterServiceClient::InitGetCharacterCreationCatalog()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_CharacterService_GetCharacterCreationCatalog>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UCharacterServiceClient::GetCharacterCreationCatalog(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextGetCharacterCreationCatalog = StaticCastSharedPtr<GrpcContext_CharacterService_GetCharacterCreationCatalog>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextGetCharacterCreationCatalog->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextGetCharacterCreationCatalog->RpcContext->set_deadline(deadLine);
		}
		contextGetCharacterCreationCatalog->Call(Request);
	}
}

FGrpcContextHandle UCharacterServiceClient::InitCreateCharacter()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_CharacterService_CreateCharacter>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UCharacterServiceClient::CreateCharacter(FGrpcContextHandle Handle, const FGrpcCharactersCreateCharacterRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextCreateCharacter = StaticCastSharedPtr<GrpcContext_CharacterService_CreateCharacter>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextCreateCharacter->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextCreateCharacter->RpcContext->set_deadline(deadLine);
		}
		contextCreateCharacter->Call(Request);
	}
}

FGrpcContextHandle UCharacterServiceClient::InitListCreatedCharacters()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_CharacterService_ListCreatedCharacters>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UCharacterServiceClient::ListCreatedCharacters(FGrpcContextHandle Handle, const FGrpcCharactersListCreatedCharactersRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextListCreatedCharacters = StaticCastSharedPtr<GrpcContext_CharacterService_ListCreatedCharacters>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextListCreatedCharacters->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextListCreatedCharacters->RpcContext->set_deadline(deadLine);
		}
		contextListCreatedCharacters->Call(Request);
	}
}

void UCharacterServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UCharacterServiceClient::Shutdown()
{
	OnCheckCharacterCreationCatalogVersionResponse.Clear();
	OnGetCharacterCreationCatalogResponse.Clear();
	OnCreateCharacterResponse.Clear();
	OnListCreatedCharactersResponse.Clear();
	Super::Shutdown();
}

