//Generated by TurboLink CodeGenerator, do not edit!
#include "SCharacters/CharactersMessage.h"
#include "SCharacters/CharactersMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcCharactersCheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionRequest)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersCheckCharacterCreationCatalogVersionResponse, ::characters::CheckCharacterCreationCatalogVersionResponse)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersRaceOption, ::characters::RaceOption)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersGenderOption, ::characters::GenderOption)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersSkinColorOption, ::characters::SkinColorOption)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersClassOption, ::characters::ClassOption)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersRaceGenderCombination, ::characters::RaceGenderCombination)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersRaceGenderSkinColorCombination, ::characters::RaceGenderSkinColorCombination)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersRaceGenderClassCombination, ::characters::RaceGenderClassCombination)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersCharacterCreationCatalog, ::characters::CharacterCreationCatalog)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersCreateCharacterRequest, ::characters::CreateCharacterRequest)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersCreateCharacterResponse, ::characters::CreateCharacterResponse)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersListCreatedCharactersRequest, ::characters::ListCreatedCharactersRequest)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersCharacter, ::characters::Character)
DEFINE_JSON_FUNCTIONS(FGrpcCharactersListCreatedCharactersResponse, ::characters::ListCreatedCharactersResponse)

