//Generated by TurboLink CodeGenerator, do not edit!
#include "CharactersMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"

void GRPC_TO_TURBOLINK(const ::characters::CheckCharacterCreationCatalogVersionRequest* in, FGrpcCharactersCheckCharacterCreationCatalogVersionRequest* out)
{
    out->CachedVersion=StringCast<TCHAR>((const UTF8CHAR*)(in->cached_version().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest* in, ::characters::CheckCharacterCreationCatalogVersionRequest* out)
{
    out->set_cached_version((const char*)StringCast<UTF8CHAR>(*(in->CachedVersion)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::CheckCharacterCreationCatalogVersionResponse* in, FGrpcCharactersCheckCharacterCreationCatalogVersionResponse* out)
{
    out->IsCurrent=in->is_current();
    out->LatestVersion=StringCast<TCHAR>((const UTF8CHAR*)(in->latest_version().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse* in, ::characters::CheckCharacterCreationCatalogVersionResponse* out)
{
    out->set_is_current(in->IsCurrent);
    out->set_latest_version((const char*)StringCast<UTF8CHAR>(*(in->LatestVersion)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::RaceOption* in, FGrpcCharactersRaceOption* out)
{
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceOption* in, ::characters::RaceOption* out)
{
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::GenderOption* in, FGrpcCharactersGenderOption* out)
{
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersGenderOption* in, ::characters::GenderOption* out)
{
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::SkinColorOption* in, FGrpcCharactersSkinColorOption* out)
{
    out->SkinColor=StaticCast<EGrpcCharactersSkinColor>(in->skin_color());
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersSkinColorOption* in, ::characters::SkinColorOption* out)
{
    out->set_skin_color(::characters::SkinColor(static_cast<uint8>(in->SkinColor)));
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::ClassOption* in, FGrpcCharactersClassOption* out)
{
    out->CharacterClass=StaticCast<EGrpcCharactersCharacterClass>(in->character_class());
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersClassOption* in, ::characters::ClassOption* out)
{
    out->set_character_class(::characters::CharacterClass(static_cast<uint8>(in->CharacterClass)));
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderCombination* in, FGrpcCharactersRaceGenderCombination* out)
{
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderCombination* in, ::characters::RaceGenderCombination* out)
{
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
}

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderSkinColorCombination* in, FGrpcCharactersRaceGenderSkinColorCombination* out)
{
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->SkinColor=StaticCast<EGrpcCharactersSkinColor>(in->skin_color());
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderSkinColorCombination* in, ::characters::RaceGenderSkinColorCombination* out)
{
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_skin_color(::characters::SkinColor(static_cast<uint8>(in->SkinColor)));
}

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderClassCombination* in, FGrpcCharactersRaceGenderClassCombination* out)
{
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->CharacterClass=StaticCast<EGrpcCharactersCharacterClass>(in->character_class());
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderClassCombination* in, ::characters::RaceGenderClassCombination* out)
{
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_character_class(::characters::CharacterClass(static_cast<uint8>(in->CharacterClass)));
}

void GRPC_TO_TURBOLINK(const ::characters::CharacterCreationCatalog* in, FGrpcCharactersCharacterCreationCatalog* out)
{
    out->Version=StringCast<TCHAR>((const UTF8CHAR*)(in->version().c_str())).Get();
    out->Races.Empty();
    for (int i=0; i<in->races_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->races(i)), &(out->Races.AddZeroed_GetRef()));
    }
    out->Genders.Empty();
    for (int i=0; i<in->genders_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->genders(i)), &(out->Genders.AddZeroed_GetRef()));
    }
    out->SkinColors.Empty();
    for (int i=0; i<in->skin_colors_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->skin_colors(i)), &(out->SkinColors.AddZeroed_GetRef()));
    }
    out->Classes.Empty();
    for (int i=0; i<in->classes_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->classes(i)), &(out->Classes.AddZeroed_GetRef()));
    }
    out->AllowedRaceGender.Empty();
    for (int i=0; i<in->allowed_race_gender_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->allowed_race_gender(i)), &(out->AllowedRaceGender.AddZeroed_GetRef()));
    }
    out->AllowedRaceGenderSkinColor.Empty();
    for (int i=0; i<in->allowed_race_gender_skin_color_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->allowed_race_gender_skin_color(i)), &(out->AllowedRaceGenderSkinColor.AddZeroed_GetRef()));
    }
    out->AllowedRaceGenderClass.Empty();
    for (int i=0; i<in->allowed_race_gender_class_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->allowed_race_gender_class(i)), &(out->AllowedRaceGenderClass.AddZeroed_GetRef()));
    }
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCharacterCreationCatalog* in, ::characters::CharacterCreationCatalog* out)
{
    out->set_version((const char*)StringCast<UTF8CHAR>(*(in->Version)).Get());
    for(const auto& value : in->Races) {
        TURBOLINK_TO_GRPC(&value, out->add_races());
    } 
    for(const auto& value : in->Genders) {
        TURBOLINK_TO_GRPC(&value, out->add_genders());
    } 
    for(const auto& value : in->SkinColors) {
        TURBOLINK_TO_GRPC(&value, out->add_skin_colors());
    } 
    for(const auto& value : in->Classes) {
        TURBOLINK_TO_GRPC(&value, out->add_classes());
    } 
    for(const auto& value : in->AllowedRaceGender) {
        TURBOLINK_TO_GRPC(&value, out->add_allowed_race_gender());
    } 
    for(const auto& value : in->AllowedRaceGenderSkinColor) {
        TURBOLINK_TO_GRPC(&value, out->add_allowed_race_gender_skin_color());
    } 
    for(const auto& value : in->AllowedRaceGenderClass) {
        TURBOLINK_TO_GRPC(&value, out->add_allowed_race_gender_class());
    } 
}

void GRPC_TO_TURBOLINK(const ::characters::CreateCharacterRequest* in, FGrpcCharactersCreateCharacterRequest* out)
{
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->SkinColor=StaticCast<EGrpcCharactersSkinColor>(in->skin_color());
    out->CharacterClass=StaticCast<EGrpcCharactersCharacterClass>(in->character_class());
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCreateCharacterRequest* in, ::characters::CreateCharacterRequest* out)
{
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_skin_color(::characters::SkinColor(static_cast<uint8>(in->SkinColor)));
    out->set_character_class(::characters::CharacterClass(static_cast<uint8>(in->CharacterClass)));
}

void GRPC_TO_TURBOLINK(const ::characters::CreateCharacterResponse* in, FGrpcCharactersCreateCharacterResponse* out)
{
    out->CharacterId=StringCast<TCHAR>((const UTF8CHAR*)(in->character_id().c_str())).Get();
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->SkinColor=StaticCast<EGrpcCharactersSkinColor>(in->skin_color());
    out->CharacterClass=StaticCast<EGrpcCharactersCharacterClass>(in->character_class());
    out->CreatedAt=StringCast<TCHAR>((const UTF8CHAR*)(in->created_at().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCreateCharacterResponse* in, ::characters::CreateCharacterResponse* out)
{
    out->set_character_id((const char*)StringCast<UTF8CHAR>(*(in->CharacterId)).Get());
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_skin_color(::characters::SkinColor(static_cast<uint8>(in->SkinColor)));
    out->set_character_class(::characters::CharacterClass(static_cast<uint8>(in->CharacterClass)));
    out->set_created_at((const char*)StringCast<UTF8CHAR>(*(in->CreatedAt)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::ListCreatedCharactersRequest* in, FGrpcCharactersListCreatedCharactersRequest* out)
{
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersListCreatedCharactersRequest* in, ::characters::ListCreatedCharactersRequest* out)
{
}

void GRPC_TO_TURBOLINK(const ::characters::Character* in, FGrpcCharactersCharacter* out)
{
    out->CharacterId=StringCast<TCHAR>((const UTF8CHAR*)(in->character_id().c_str())).Get();
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
    out->Race=StaticCast<EGrpcCharactersRace>(in->race());
    out->Gender=StaticCast<EGrpcCharactersGender>(in->gender());
    out->SkinColor=StaticCast<EGrpcCharactersSkinColor>(in->skin_color());
    out->CharacterClass=StaticCast<EGrpcCharactersCharacterClass>(in->character_class());
    out->CreatedAt=StringCast<TCHAR>((const UTF8CHAR*)(in->created_at().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersCharacter* in, ::characters::Character* out)
{
    out->set_character_id((const char*)StringCast<UTF8CHAR>(*(in->CharacterId)).Get());
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
    out->set_race(::characters::Race(static_cast<uint8>(in->Race)));
    out->set_gender(::characters::Gender(static_cast<uint8>(in->Gender)));
    out->set_skin_color(::characters::SkinColor(static_cast<uint8>(in->SkinColor)));
    out->set_character_class(::characters::CharacterClass(static_cast<uint8>(in->CharacterClass)));
    out->set_created_at((const char*)StringCast<UTF8CHAR>(*(in->CreatedAt)).Get());
}

void GRPC_TO_TURBOLINK(const ::characters::ListCreatedCharactersResponse* in, FGrpcCharactersListCreatedCharactersResponse* out)
{
    out->Characters.Empty();
    for (int i=0; i<in->characters_size(); ++i) {
        GRPC_TO_TURBOLINK(&(in->characters(i)), &(out->Characters.AddZeroed_GetRef()));
    }
}

void TURBOLINK_TO_GRPC(const FGrpcCharactersListCreatedCharactersResponse* in, ::characters::ListCreatedCharactersResponse* out)
{
    for(const auto& value : in->Characters) {
        TURBOLINK_TO_GRPC(&value, out->add_characters());
    } 
}

