//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SCharacters/CharactersService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "characters.grpc.pb.h"
#include "CharactersService_Private.generated.h"

class UCharacterService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::characters::CharacterService::Stub> Stub;
};


UCLASS()
class UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UCharacterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse& Response);
public:
	FGrpcContextHandle Handle;
	UCharacterService::FCheckCharacterCreationCatalogVersionResponseLambda ResponseLambda;
};

UCLASS()
class UCharacterServiceGetCharacterCreationCatalogLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UCharacterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCharacterCreationCatalog& Response);
public:
	FGrpcContextHandle Handle;
	UCharacterService::FGetCharacterCreationCatalogResponseLambda ResponseLambda;
};

UCLASS()
class UCharacterServiceCreateCharacterLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UCharacterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCreateCharacterResponse& Response);
public:
	FGrpcContextHandle Handle;
	UCharacterService::FCreateCharacterResponseLambda ResponseLambda;
};

UCLASS()
class UCharacterServiceListCreatedCharactersLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UCharacterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersListCreatedCharactersResponse& Response);
public:
	FGrpcContextHandle Handle;
	UCharacterService::FListCreatedCharactersResponseLambda ResponseLambda;
};

