//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SCharacters/CharactersMessage.h"
#include "TurboLinkGrpcContext.h"
#include "characters.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::characters::CheckCharacterCreationCatalogVersionRequest* in, FGrpcCharactersCheckCharacterCreationCatalogVersionRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest* in, ::characters::CheckCharacterCreationCatalogVersionRequest* out);

void GRPC_TO_TURBOLINK(const ::characters::CheckCharacterCreationCatalogVersionResponse* in, FGrpcCharactersCheckCharacterCreationCatalogVersionResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse* in, ::characters::CheckCharacterCreationCatalogVersionResponse* out);

void GRPC_TO_TURBOLINK(const ::characters::RaceOption* in, FGrpcCharactersRaceOption* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceOption* in, ::characters::RaceOption* out);

void GRPC_TO_TURBOLINK(const ::characters::GenderOption* in, FGrpcCharactersGenderOption* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersGenderOption* in, ::characters::GenderOption* out);

void GRPC_TO_TURBOLINK(const ::characters::SkinColorOption* in, FGrpcCharactersSkinColorOption* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersSkinColorOption* in, ::characters::SkinColorOption* out);

void GRPC_TO_TURBOLINK(const ::characters::ClassOption* in, FGrpcCharactersClassOption* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersClassOption* in, ::characters::ClassOption* out);

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderCombination* in, FGrpcCharactersRaceGenderCombination* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderCombination* in, ::characters::RaceGenderCombination* out);

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderSkinColorCombination* in, FGrpcCharactersRaceGenderSkinColorCombination* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderSkinColorCombination* in, ::characters::RaceGenderSkinColorCombination* out);

void GRPC_TO_TURBOLINK(const ::characters::RaceGenderClassCombination* in, FGrpcCharactersRaceGenderClassCombination* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersRaceGenderClassCombination* in, ::characters::RaceGenderClassCombination* out);

void GRPC_TO_TURBOLINK(const ::characters::CharacterCreationCatalog* in, FGrpcCharactersCharacterCreationCatalog* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCharacterCreationCatalog* in, ::characters::CharacterCreationCatalog* out);

void GRPC_TO_TURBOLINK(const ::characters::CreateCharacterRequest* in, FGrpcCharactersCreateCharacterRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCreateCharacterRequest* in, ::characters::CreateCharacterRequest* out);

void GRPC_TO_TURBOLINK(const ::characters::CreateCharacterResponse* in, FGrpcCharactersCreateCharacterResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCreateCharacterResponse* in, ::characters::CreateCharacterResponse* out);

void GRPC_TO_TURBOLINK(const ::characters::ListCreatedCharactersRequest* in, FGrpcCharactersListCreatedCharactersRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersListCreatedCharactersRequest* in, ::characters::ListCreatedCharactersRequest* out);

void GRPC_TO_TURBOLINK(const ::characters::Character* in, FGrpcCharactersCharacter* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersCharacter* in, ::characters::Character* out);

void GRPC_TO_TURBOLINK(const ::characters::ListCreatedCharactersResponse* in, FGrpcCharactersListCreatedCharactersResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcCharactersListCreatedCharactersResponse* in, ::characters::ListCreatedCharactersResponse* out);

typedef grpc::ClientAsyncResponseReader<::characters::CheckCharacterCreationCatalogVersionResponse> CharacterService_CheckCharacterCreationCatalogVersion_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::characters::CharacterCreationCatalog> CharacterService_GetCharacterCreationCatalog_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::characters::CreateCharacterResponse> CharacterService_CreateCharacter_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::characters::ListCreatedCharactersResponse> CharacterService_ListCreatedCharacters_ReaderWriter;
