//Generated by TurboLink CodeGenerator, do not edit!
#include "CharactersService_Private.h"

void UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCheckCharacterCreationCatalogVersionResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCheckCharacterCreationCatalogVersionResponse.RemoveDynamic(this, &UCharacterServiceCheckCharacterCreationCatalogVersionLambdaWrapper::OnResponse);
}

void UCharacterServiceGetCharacterCreationCatalogLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCharacterCreationCatalog& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetCharacterCreationCatalogResponse.RemoveDynamic(this, &UCharacterServiceGetCharacterCreationCatalogLambdaWrapper::OnResponse);
}

void UCharacterServiceCreateCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersCreateCharacterResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCreateCharacterResponse.RemoveDynamic(this, &UCharacterServiceCreateCharacterLambdaWrapper::OnResponse);
}

void UCharacterServiceListCreatedCharactersLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcCharactersListCreatedCharactersResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnListCreatedCharactersResponse.RemoveDynamic(this, &UCharacterServiceListCreatedCharactersLambdaWrapper::OnResponse);
}

