//Generated by TurboLink CodeGenerator, do not edit!
#include "CharactersContext.h"
#include "SCharacters/CharactersClient.h"
#include "CharactersService_Private.h"
#include "CharactersMarshaling.h"
#include "SGoogleProtobuf/EmptyMarshaling.h"
#include "TurboLinkGrpcManager.h"

GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion::GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion::Call(const FGrpcCharactersCheckCharacterCreationCatalogVersionRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::characters::CheckCharacterCreationCatalogVersionRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncCheckCharacterCreationCatalogVersion(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_CheckCharacterCreationCatalogVersion::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::characters::CheckCharacterCreationCatalogVersionResponse* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnCheckCharacterCreationCatalogVersionResponse.IsBound())) return;

			FGrpcCharactersCheckCharacterCreationCatalogVersionResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnCheckCharacterCreationCatalogVersionResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_GetCharacterCreationCatalog::GrpcContext_CharacterService_GetCharacterCreationCatalog(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_GetCharacterCreationCatalog::Call(const FGrpcGoogleProtobufEmpty& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::google::protobuf::Empty rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncGetCharacterCreationCatalog(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_GetCharacterCreationCatalog::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::characters::CharacterCreationCatalog* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnGetCharacterCreationCatalogResponse.IsBound())) return;

			FGrpcCharactersCharacterCreationCatalog response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnGetCharacterCreationCatalogResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_CreateCharacter::GrpcContext_CharacterService_CreateCharacter(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_CreateCharacter::Call(const FGrpcCharactersCreateCharacterRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::characters::CreateCharacterRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncCreateCharacter(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_CreateCharacter::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::characters::CreateCharacterResponse* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnCreateCharacterResponse.IsBound())) return;

			FGrpcCharactersCreateCharacterResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnCreateCharacterResponse.Broadcast(Handle, _Result, response);
		}
	);
}

GrpcContext_CharacterService_ListCreatedCharacters::GrpcContext_CharacterService_ListCreatedCharacters(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_CharacterService_ListCreatedCharacters::Call(const FGrpcCharactersListCreatedCharactersRequest& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::characters::ListCreatedCharactersRequest rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UCharacterService* service = (UCharacterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncListCreatedCharacters(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_CharacterService_ListCreatedCharacters::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::characters::ListCreatedCharactersResponse* _RpcResponse) 
		{
			UCharacterServiceClient* client = (UCharacterServiceClient*)(this->Client);
			if (!(client->OnListCreatedCharactersResponse.IsBound())) return;

			FGrpcCharactersListCreatedCharactersResponse response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnListCreatedCharactersResponse.Broadcast(Handle, _Result, response);
		}
	);
}
