// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: characters.proto
#ifndef GRPC_characters_2eproto__INCLUDED
#define GRPC_characters_2eproto__INCLUDED

#include "characters.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace characters {

// Character service definition
class CharacterService final {
 public:
  static constexpr char const* service_full_name() {
    return "characters.CharacterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::characters::CheckCharacterCreationCatalogVersionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>> AsyncCheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>>(AsyncCheckCharacterCreationCatalogVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>> PrepareAsyncCheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>>(PrepareAsyncCheckCharacterCreationCatalogVersionRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::characters::CharacterCreationCatalog* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>> AsyncGetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>>(AsyncGetCharacterCreationCatalogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>> PrepareAsyncGetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>>(PrepareAsyncGetCharacterCreationCatalogRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::characters::CreateCharacterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>> AsyncCreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>>(AsyncCreateCharacterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>> PrepareAsyncCreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>>(PrepareAsyncCreateCharacterRaw(context, request, cq));
    }
    virtual ::grpc::Status ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::characters::ListCreatedCharactersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>> AsyncListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>>(AsyncListCreatedCharactersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>> PrepareAsyncListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>>(PrepareAsyncListCreatedCharactersRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>* AsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CheckCharacterCreationCatalogVersionResponse>* PrepareAsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>* AsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CharacterCreationCatalog>* PrepareAsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>* AsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::CreateCharacterResponse>* PrepareAsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>* AsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::characters::ListCreatedCharactersResponse>* PrepareAsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::characters::CheckCharacterCreationCatalogVersionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>> AsyncCheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>>(AsyncCheckCharacterCreationCatalogVersionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>> PrepareAsyncCheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>>(PrepareAsyncCheckCharacterCreationCatalogVersionRaw(context, request, cq));
    }
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::characters::CharacterCreationCatalog* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>> AsyncGetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>>(AsyncGetCharacterCreationCatalogRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>> PrepareAsyncGetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>>(PrepareAsyncGetCharacterCreationCatalogRaw(context, request, cq));
    }
    ::grpc::Status CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::characters::CreateCharacterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>> AsyncCreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>>(AsyncCreateCharacterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>> PrepareAsyncCreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>>(PrepareAsyncCreateCharacterRaw(context, request, cq));
    }
    ::grpc::Status ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::characters::ListCreatedCharactersResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>> AsyncListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>>(AsyncListCreatedCharactersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>> PrepareAsyncListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>>(PrepareAsyncListCreatedCharactersRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, std::function<void(::grpc::Status)>) override;
      void GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, std::function<void(::grpc::Status)>) override;
      void ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>* AsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>* PrepareAsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>* AsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>* PrepareAsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>* AsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>* PrepareAsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>* AsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>* PrepareAsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckCharacterCreationCatalogVersion_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCharacterCreationCatalog_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateCharacter_;
    const ::grpc::internal::RpcMethod rpcmethod_ListCreatedCharacters_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response);
    virtual ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response);
    virtual ::grpc::Status CreateCharacter(::grpc::ServerContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response);
    virtual ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCharacterCreationCatalogVersion(::grpc::ServerContext* context, ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::grpc::ServerAsyncResponseWriter< ::characters::CheckCharacterCreationCatalogVersionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCharacterCreationCatalog(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::characters::CharacterCreationCatalog>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateCharacter(::grpc::ServerContext* context, ::characters::CreateCharacterRequest* request, ::grpc::ServerAsyncResponseWriter< ::characters::CreateCharacterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCreatedCharacters(::grpc::ServerContext* context, ::characters::ListCreatedCharactersRequest* request, ::grpc::ServerAsyncResponseWriter< ::characters::ListCreatedCharactersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckCharacterCreationCatalogVersion<WithAsyncMethod_GetCharacterCreationCatalog<WithAsyncMethod_CreateCharacter<WithAsyncMethod_ListCreatedCharacters<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response) { return this->CheckCharacterCreationCatalogVersion(context, request, response); }));}
    void SetMessageAllocatorFor_CheckCharacterCreationCatalogVersion(
        ::grpc::MessageAllocator< ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckCharacterCreationCatalogVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::characters::CharacterCreationCatalog>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response) { return this->GetCharacterCreationCatalog(context, request, response); }));}
    void SetMessageAllocatorFor_GetCharacterCreationCatalog(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::characters::CharacterCreationCatalog>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::characters::CharacterCreationCatalog>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCharacterCreationCatalog(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response) { return this->CreateCharacter(context, request, response); }));}
    void SetMessageAllocatorFor_CreateCharacter(
        ::grpc::MessageAllocator< ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateCharacter(
      ::grpc::CallbackServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response) { return this->ListCreatedCharacters(context, request, response); }));}
    void SetMessageAllocatorFor_ListCreatedCharacters(
        ::grpc::MessageAllocator< ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCreatedCharacters(
      ::grpc::CallbackServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckCharacterCreationCatalogVersion<WithCallbackMethod_GetCharacterCreationCatalog<WithCallbackMethod_CreateCharacter<WithCallbackMethod_ListCreatedCharacters<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckCharacterCreationCatalogVersion(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCharacterCreationCatalog(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateCharacter(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCreatedCharacters(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckCharacterCreationCatalogVersion(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckCharacterCreationCatalogVersion(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCharacterCreationCatalog(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCharacterCreationCatalog(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateCharacter(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateCharacter(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListCreatedCharacters(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCreatedCharacters(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckCharacterCreationCatalogVersion : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckCharacterCreationCatalogVersion() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse>* streamer) {
                       return this->StreamedCheckCharacterCreationCatalogVersion(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckCharacterCreationCatalogVersion() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckCharacterCreationCatalogVersion(::grpc::ServerContext* /*context*/, const ::characters::CheckCharacterCreationCatalogVersionRequest* /*request*/, ::characters::CheckCharacterCreationCatalogVersionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckCharacterCreationCatalogVersion(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::characters::CheckCharacterCreationCatalogVersionRequest,::characters::CheckCharacterCreationCatalogVersionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCharacterCreationCatalog : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCharacterCreationCatalog() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::characters::CharacterCreationCatalog>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::characters::CharacterCreationCatalog>* streamer) {
                       return this->StreamedGetCharacterCreationCatalog(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCharacterCreationCatalog() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCharacterCreationCatalog(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::characters::CharacterCreationCatalog* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCharacterCreationCatalog(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::characters::CharacterCreationCatalog>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateCharacter : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateCharacter() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse>* streamer) {
                       return this->StreamedCreateCharacter(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateCharacter() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateCharacter(::grpc::ServerContext* /*context*/, const ::characters::CreateCharacterRequest* /*request*/, ::characters::CreateCharacterResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateCharacter(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::characters::CreateCharacterRequest,::characters::CreateCharacterResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListCreatedCharacters : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListCreatedCharacters() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse>* streamer) {
                       return this->StreamedListCreatedCharacters(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListCreatedCharacters() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListCreatedCharacters(::grpc::ServerContext* /*context*/, const ::characters::ListCreatedCharactersRequest* /*request*/, ::characters::ListCreatedCharactersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListCreatedCharacters(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::characters::ListCreatedCharactersRequest,::characters::ListCreatedCharactersResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckCharacterCreationCatalogVersion<WithStreamedUnaryMethod_GetCharacterCreationCatalog<WithStreamedUnaryMethod_CreateCharacter<WithStreamedUnaryMethod_ListCreatedCharacters<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckCharacterCreationCatalogVersion<WithStreamedUnaryMethod_GetCharacterCreationCatalog<WithStreamedUnaryMethod_CreateCharacter<WithStreamedUnaryMethod_ListCreatedCharacters<Service > > > > StreamedService;
};

}  // namespace characters


#endif  // GRPC_characters_2eproto__INCLUDED
