// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: characters.proto

#include "characters.pb.h"
#include "characters.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace characters {

static const char* CharacterService_method_names[] = {
  "/characters.CharacterService/CheckCharacterCreationCatalogVersion",
  "/characters.CharacterService/GetCharacterCreationCatalog",
  "/characters.CharacterService/CreateCharacter",
  "/characters.CharacterService/ListCreatedCharacters",
};

std::unique_ptr< CharacterService::Stub> CharacterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CharacterService::Stub> stub(new CharacterService::Stub(channel, options));
  return stub;
}

CharacterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckCharacterCreationCatalogVersion_(CharacterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCharacterCreationCatalog_(CharacterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateCharacter_(CharacterService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListCreatedCharacters_(CharacterService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CharacterService::Stub::CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::characters::CheckCharacterCreationCatalogVersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckCharacterCreationCatalogVersion_, context, request, response);
}

void CharacterService::Stub::async::CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCharacterCreationCatalogVersion_, context, request, response, std::move(f));
}

void CharacterService::Stub::async::CheckCharacterCreationCatalogVersion(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCharacterCreationCatalogVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>* CharacterService::Stub::PrepareAsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::characters::CheckCharacterCreationCatalogVersionResponse, ::characters::CheckCharacterCreationCatalogVersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckCharacterCreationCatalogVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::characters::CheckCharacterCreationCatalogVersionResponse>* CharacterService::Stub::AsyncCheckCharacterCreationCatalogVersionRaw(::grpc::ClientContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckCharacterCreationCatalogVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CharacterService::Stub::GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::characters::CharacterCreationCatalog* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::characters::CharacterCreationCatalog, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCharacterCreationCatalog_, context, request, response);
}

void CharacterService::Stub::async::GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::characters::CharacterCreationCatalog, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCharacterCreationCatalog_, context, request, response, std::move(f));
}

void CharacterService::Stub::async::GetCharacterCreationCatalog(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCharacterCreationCatalog_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>* CharacterService::Stub::PrepareAsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::characters::CharacterCreationCatalog, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCharacterCreationCatalog_, context, request);
}

::grpc::ClientAsyncResponseReader< ::characters::CharacterCreationCatalog>* CharacterService::Stub::AsyncGetCharacterCreationCatalogRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCharacterCreationCatalogRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CharacterService::Stub::CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::characters::CreateCharacterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateCharacter_, context, request, response);
}

void CharacterService::Stub::async::CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacter_, context, request, response, std::move(f));
}

void CharacterService::Stub::async::CreateCharacter(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>* CharacterService::Stub::PrepareAsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::characters::CreateCharacterResponse, ::characters::CreateCharacterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateCharacter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::characters::CreateCharacterResponse>* CharacterService::Stub::AsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::characters::CreateCharacterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateCharacterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CharacterService::Stub::ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::characters::ListCreatedCharactersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListCreatedCharacters_, context, request, response);
}

void CharacterService::Stub::async::ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCreatedCharacters_, context, request, response, std::move(f));
}

void CharacterService::Stub::async::ListCreatedCharacters(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListCreatedCharacters_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>* CharacterService::Stub::PrepareAsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::characters::ListCreatedCharactersResponse, ::characters::ListCreatedCharactersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListCreatedCharacters_, context, request);
}

::grpc::ClientAsyncResponseReader< ::characters::ListCreatedCharactersResponse>* CharacterService::Stub::AsyncListCreatedCharactersRaw(::grpc::ClientContext* context, const ::characters::ListCreatedCharactersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListCreatedCharactersRaw(context, request, cq);
  result->StartCall();
  return result;
}

CharacterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CharacterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CharacterService::Service, ::characters::CheckCharacterCreationCatalogVersionRequest, ::characters::CheckCharacterCreationCatalogVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CharacterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::characters::CheckCharacterCreationCatalogVersionRequest* req,
             ::characters::CheckCharacterCreationCatalogVersionResponse* resp) {
               return service->CheckCharacterCreationCatalogVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CharacterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CharacterService::Service, ::google::protobuf::Empty, ::characters::CharacterCreationCatalog, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CharacterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::characters::CharacterCreationCatalog* resp) {
               return service->GetCharacterCreationCatalog(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CharacterService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CharacterService::Service, ::characters::CreateCharacterRequest, ::characters::CreateCharacterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CharacterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::characters::CreateCharacterRequest* req,
             ::characters::CreateCharacterResponse* resp) {
               return service->CreateCharacter(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CharacterService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CharacterService::Service, ::characters::ListCreatedCharactersRequest, ::characters::ListCreatedCharactersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CharacterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::characters::ListCreatedCharactersRequest* req,
             ::characters::ListCreatedCharactersResponse* resp) {
               return service->ListCreatedCharacters(ctx, req, resp);
             }, this)));
}

CharacterService::Service::~Service() {
}

::grpc::Status CharacterService::Service::CheckCharacterCreationCatalogVersion(::grpc::ServerContext* context, const ::characters::CheckCharacterCreationCatalogVersionRequest* request, ::characters::CheckCharacterCreationCatalogVersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CharacterService::Service::GetCharacterCreationCatalog(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::characters::CharacterCreationCatalog* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CharacterService::Service::CreateCharacter(::grpc::ServerContext* context, const ::characters::CreateCharacterRequest* request, ::characters::CreateCharacterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CharacterService::Service::ListCreatedCharacters(::grpc::ServerContext* context, const ::characters::ListCreatedCharactersRequest* request, ::characters::ListCreatedCharactersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace characters

