//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "AuthMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Auth.LoginStatus", ScriptName="EGrpcAuthLoginStatus"))
enum class EGrpcAuthLoginStatus : uint8
{
    SUCCESS=0,
    FAILURE=1,
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.LoginRequest"))
struct FGrpcAuthLoginRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Username = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.LoginResponse"))
struct FGrpcAuthLoginResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcAuthLoginStatus Status = static_cast<EGrpcAuthLoginStatus>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Message = "";
};
