//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "AuthMessage.h"
#include "AuthNode.generated.h"

class UAuthService;
class UAuthServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallAuthServiceLogin : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FAuthServiceLoginDelegate, const FGrpcResult&, GrpcResult, const FGrpcAuthLoginResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|AuthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call AuthService Login",
		AdvancedDisplay = 2))
	static UCallAuthServiceLogin* Login(UObject* WorldContextObject, const FGrpcAuthLoginRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FAuthServiceLoginDelegate OnLoginResponse;

	UPROPERTY(BlueprintAssignable)
	FAuthServiceLoginDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UAuthService* AuthService;
	
	UPROPERTY()
	UAuthServiceClient* AuthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcAuthLoginRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcAuthLoginResponse& Response);

	void Shutdown();
};
